version: "3"

interval: 500ms

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list-all
    silent: true

  update:
    desc: Update submodules
    cmds:
      - git submodule update --init --recursive

  db:
    desc: Apply database migrations
    cmds:
      - goose up
      - jet -source=sqlite -dsn="$HOKEY_DB_FILE" -path=db/query
    sources:
      - db/migrations/*.sql

  start:
    desc: Start the server
    cmds:
      - go run .
