//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Card struct {
	ID          *int32 `sql:"primary_key"`
	PtcgID      string
	Name        string
	Metadata    *string
	GroupID     int32
	SupertypeID int32
}
