//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Card = Card.FromSchema(schema)
	CardCollection = CardCollection.FromSchema(schema)
	CardType = CardType.FromSchema(schema)
	Collection = Collection.FromSchema(schema)
	CollectionEnergy = CollectionEnergy.FromSchema(schema)
	Group = Group.FromSchema(schema)
	GroupType = GroupType.FromSchema(schema)
	Supertype = Supertype.FromSchema(schema)
	Type = Type.FromSchema(schema)
	GooseDbVersion = GooseDbVersion.FromSchema(schema)
}
