//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Type = newTypeTable("", "Type", "")

type typeTable struct {
	sqlite.Table

	// Columns
	ID   sqlite.ColumnInteger
	Name sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type TypeTable struct {
	typeTable

	EXCLUDED typeTable
}

// AS creates new TypeTable with assigned alias
func (a TypeTable) AS(alias string) *TypeTable {
	return newTypeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TypeTable with assigned schema name
func (a TypeTable) FromSchema(schemaName string) *TypeTable {
	return newTypeTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TypeTable with assigned table prefix
func (a TypeTable) WithPrefix(prefix string) *TypeTable {
	return newTypeTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TypeTable with assigned table suffix
func (a TypeTable) WithSuffix(suffix string) *TypeTable {
	return newTypeTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTypeTable(schemaName, tableName, alias string) *TypeTable {
	return &TypeTable{
		typeTable: newTypeTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newTypeTableImpl("", "excluded", ""),
	}
}

func newTypeTableImpl(schemaName, tableName, alias string) typeTable {
	var (
		IDColumn       = sqlite.IntegerColumn("id")
		NameColumn     = sqlite.StringColumn("name")
		allColumns     = sqlite.ColumnList{IDColumn, NameColumn}
		mutableColumns = sqlite.ColumnList{NameColumn}
	)

	return typeTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:   IDColumn,
		Name: NameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
